### ISSUE TITLE
add() method - Allow custom curves without duration

### ISSUE THREAD

**Issue by benPesso** [felixblaschke/sa_multi_tween#1]
Love the changes in v2!

However, the new structure requires you to specify duration if you want to have a custom curve, which forces you to do something like...
```dart
// This:
..add('scale', Tween(begin: 0.0, end: 1.0), Duration(seconds: 0), Curves.decelerate);
// ...or this: 
..add('scale', Tween(begin: 0.0, end: 1.0)..curved(Curves.decelerate));
```

While the second workaround is readable, it is not as semantic as this:
```dart
..add('scale', Tween(begin: 0.0, end: 1.0), curves: Curves.decelerate);
```
or at the very least, this:
```dart
..add('scale', Tween(begin: 0.0, end: 1.0), _, Curves.decelerate);
```

**Comment by felixblaschke** [comment]
Thank you for your feedback. I made a little change to MultiTween. Instead of only accepting `Tween` it also accepts it's superclass `Animatable`. You'll need Simple Animations `2.2.0`.

Then with [supercharged](https://pub.dev/packages/supercharged) (also a package I maintain) you apply a curve on any tween:

```dart
var _tween = MultiTween<P>()
  ..add(P.scale, 0.0.tweenTo(1.0).curved(Curves.decelerate));
```

You can also use the `.curved()` method without MultiTween.

I made a fully working example for you:
```dart
import 'package:flutter/material.dart';
import 'package:simple_animations/simple_animations.dart';
import 'package:supercharged/supercharged.dart';

main() => runApp(MyApp());

enum P { scale }

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var _tween = MultiTween<P>()
      ..add(P.scale, 0.0.tweenTo(1.0).curved(Curves.decelerate));

    return MaterialApp(
      home: Scaffold(
          body: Center(
        child: LoopAnimation<MultiTweenValues<P>>(
          tween: _tween,
          duration: 1.seconds,
          builder: (context, child, value) {
            return Container(
                width: 100 * value.get(P.scale),
                height: 100 * value.get(P.scale),
                color: Colors.green);
          },
        ),
      )),
    );
  }
}
```

**Comment by benPesso** [comment]
Nice! Using Animatable is a good flexibility to add. However, it is still less verbose to use `curved()`, as opposed to a parameter within the `add()` method. I'm using the cascade on the Tween, so there isn't much of a difference between that and the change you just made. (It's exactly a one character difference, actually. 😄)

I can close this issue, if you feel it's a good enough solution. I can live with the cascading. :)
